apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stl-pinn-ingress
  namespace: stl-pinn-processor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.stl-pinn-processor.com
    secretName: stl-pinn-tls
  rules:
  - host: api.stl-pinn-processor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stl-pinn-api-service
            port:
              number: 80
