apiVersion: v1
kind: Service
metadata:
  name: stl-pinn-api-service
  namespace: stl-pinn-processor
  labels:
    app: stl-pinn-api
spec:
  selector:
    app: stl-pinn-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
